/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.grandland.glits.ms.protocol;

@SuppressWarnings("all")
/** Protocol Heartbeat */
@org.apache.avro.specific.AvroGenerated
public interface HeartbeatProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"HeartbeatProtocol\",\"namespace\":\"com.grandland.glits.ms.protocol\",\"doc\":\"Protocol Heartbeat\",\"types\":[{\"type\":\"record\",\"name\":\"HeartbeatRequest\",\"fields\":[{\"name\":\"version\",\"type\":\"int\"},{\"name\":\"host_name\",\"type\":\"string\"},{\"name\":\"total_cpu\",\"type\":\"double\"},{\"name\":\"memory_usage\",\"type\":\"double\"},{\"name\":\"processes\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"mounted_avail_space\",\"type\":{\"type\":\"map\",\"values\":\"long\"}}]},{\"type\":\"record\",\"name\":\"HeartbeatResponse\",\"fields\":[{\"name\":\"host_name\",\"type\":\"string\"},{\"name\":\"heartbeat_interval\",\"type\":\"long\"},{\"name\":\"processes\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"extra_configs\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}],\"messages\":{\"heartbeat\":{\"request\":[{\"name\":\"request\",\"type\":\"HeartbeatRequest\"}],\"response\":\"HeartbeatResponse\"}}}");
  com.grandland.glits.ms.protocol.HeartbeatResponse heartbeat(com.grandland.glits.ms.protocol.HeartbeatRequest request) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** Protocol Heartbeat */
  public interface Callback extends HeartbeatProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = HeartbeatProtocol.PROTOCOL;
    void heartbeat(com.grandland.glits.ms.protocol.HeartbeatRequest request, org.apache.avro.ipc.Callback<com.grandland.glits.ms.protocol.HeartbeatResponse> callback) throws java.io.IOException;
  }
}